server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #Entity변수명 그대로 입력
      use-new-id-generator-mappings: false  #JPA의 기본전략을 따라하지 않겠다고 설정  ID 자동부여 전략
    show-sql: true
    properties:
      hibbernate.format_sql: true  #쿼리문이 여러줄로 표현

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.  /indiak0710@gmail.com
            client-id: 249309086126-mc8t6n7ffdlcfnu3ov66372bndqnmbgt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook: # /oauth2/authorization/google 이 주소를 동작하게 한다.  /indiak0710@gmail.com
            client-id: 1102038777030984
            client-secret: 66fb96ede7f0ee3d26a184092642ec54
            scope:
              - email
              - public_profile

          naver:
            clientId: fNhNRINi2daxOuDOxxu8
            clientSecret: NsHVfcvEbE
            scope:
              - name
              - email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: 91e7da20f1bb3a3910c6194bac673fd9
            client-secret: yjqOBMJUGDLeruZc2QR7nyaPlZPNA3jv
            client-name: kakao
            authorization-grant-type: authorization_code
            clientAuthenticationMethod: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 JSON으로 받는데 response라는 키를

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id